const NO_TEAM_PROVIDED = 'NO_TEAM_PROVIDED';
const NO_GAMES_FOUND = 'NO_GAMES_FOUND';
const NO_TEAM_FOUND = 'NO_TEAM_FOUND';
const INVALID_TEAM_NAME = 'INVALID_TEAM_NAME';
const UNPARSEABLE_DATE = 'UNPARSEABLE_DATE';

module.exports = {
	NO_TEAM_PROVIDED,
	NO_GAMES_FOUND,
	NO_TEAM_FOUND,
	INVALID_TEAM_NAME,
	UNPARSEABLE_DATE
};
